[package]
name = "rustyblog"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.12.1"
tokio = { version = "1.11.0", features = ["full"] }
warp = "0.3.1"